apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: canary-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'fastapi-app'
        static_configs:
          - targets: ['fastapi-service.canary-demo.svc.cluster.local:8001']
