apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: canary-demo
spec:
  metrics:
  - name: error-rate
    interval: 30s
    successCondition: result < 0.1
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus.canary-demo.svc.cluster.local:9090
        query: |
          sum(rate(http_requests_total{status=~"5.."}[1m])) /
          sum(rate(http_requests_total[1m]))
